# Generated by Django 5.0.2 on 2024-03-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='categories',
            field=models.CharField(choices=[('Fsh', 'Fashion'), ('Ty', 'Toys'), ('Elec', 'Electronics'), ('Book', 'Books'), ('sports', 'Sports'), ('', 'None')], default='', max_length=64),
        ),
    ]
