# Generated by Django 5.0.2 on 2024-03-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='categories',
            field=models.CharField(blank=True, choices=[('Fsh', 'Fashion'), ('Ty', 'Toys'), ('Elec', 'Electronics'), ('Book', 'Books'), ('sports', 'Sports'), ('', 'None')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
