# Generated by Django 5.0.2 on 2024-03-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auctionlisting_watchlist_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watchProduct',
            new_name='products',
        ),
    ]
