# Generated by Django 5.0.2 on 2024-03-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_watchlist_products_alter_watchlist_watchuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
