# Generated by Django 5.0.2 on 2024-03-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auctionlisting_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('Sports', 'Sports'), ('', 'None')], default='', max_length=64),
        ),
    ]
