# Generated by Django 5.0.2 on 2024-03-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, choices=[('Fsh', 'Fashion'), ('Ty', 'Toys'), ('Elec', 'Electronics'), ('Book', 'Books'), ('sports', 'Sports'), ('', 'None')], default='', max_length=64),
        ),
    ]
